### PR TITLE
[14.0][FIX] fcd_purchase_order: Licenses changed and some fixes

### PR DESCRIPTION
**Pull request by adriresu**

### CODE REVIEW

**Review by dalonsod — APPROVED** [review]
👍 

@ChristianSantamaria is it ready to be merged?

**Comment by ChristianSantamaria** [comment]
An error appears without information in the case of printing the product tag report if the order is not confirmed can you see it @adriresu?
imagen

**Comment by adriresu** [comment]
The problem was due to that the purchase orders were not being filtered in the report, so they did not have the date_approve field. Fixed.

**Review by ChristianSantamaria — APPROVED** [review]
LGTM 👍

**Review by dalonsod — APPROVED** [review]
👍

**Pull request merged**
